version: '3.8'
services:
    redis:
        image: 'redis:5.0.5'
        container_name: redis_airflow
        environment:
            - SET_CONTAINER_TIMEZONE=true
            - CONTAINER_TIMEZONE=Asia/Jakarta
            - TZ=Asia/Jakarta
        command: redis-server --requirepass redispass

    postgres:
        image: postgres:9.6
        container_name: postgres_airflow
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - PGDATA=/var/lib/postgresql/data/pgdata
            - SET_CONTAINER_TIMEZONE=true
            - CONTAINER_TIMEZONE=Asia/Jakarta
            - TZ=Asia/Jakarta
        volumes:
            - ./ciput_airflow/postgres:/var/lib/postgresql/data/pgdata

    webserver:
        build:
            context: docker/airflow
        image: ciput/docker-airflow:1.10.9
        container_name: webserver_airflow
        restart: always
        depends_on:
            - postgres
            - redis
        environment:
            - SET_CONTAINER_TIMEZONE=true
            - CONTAINER_TIMEZONE=Asia/Jakarta
            - TZ=Asia/Jakarta
            - LOAD_EX=n
            - EXECUTOR=Celery  
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow 
            - POSTGRES_DB=airflow
            - REDIS_PASSWORD=redispass
        volumes:
            - ./ciput_airflow/airflow/dags:/usr/local/airflow/dags
            - ./ciput_airflow/airflow/airflow.cfg:/usr/local/airflow/airflow.cfg
            - ./ciput_airflow/airflow/plugins:/usr/local/airflow/plugins
        ports:
            - "8083:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    flower:
        build:
            context: docker/airflow
        image: ciput/docker-airflow:1.10.9
        container_name: flower_airflow
        restart: always
        depends_on:
            - redis
        environment:
            - SET_CONTAINER_TIMEZONE=true
            - CONTAINER_TIMEZONE=Asia/Jakarta
            - TZ=Asia/Jakarta
            - EXECUTOR=Celery
            - REDIS_PASSWORD=redispass
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        build:
            context: docker/airflow
        image: ciput/docker-airflow:1.10.9
        container_name: scheduler_airflow
        restart: always
        depends_on:
            - webserver
        volumes:
            - ./ciput_airflow/airflow/dags:/usr/local/airflow/dags
            - ./ciput_airflow/airflow/airflow.cfg:/usr/local/airflow/airflow.cfg
            - ./ciput_airflow/airflow/plugins:/usr/local/airflow/plugins
        environment:
            - SET_CONTAINER_TIMEZONE=true
            - CONTAINER_TIMEZONE=Asia/Jakarta
            - TZ=Asia/Jakarta
            - LOAD_EX=n
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - REDIS_PASSWORD=redis
        command: scheduler

    worker:
        build:
            context: docker/airflow
        image: ciput/docker-airflow:1.10.9
        container_name: worker_airflow
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ./ciput_airflow/airflow/dags:/usr/local/airflow/dags
            - ./ciput_airflow/airflow/airflow.cfg:/usr/local/airflow/airflow.cfg
            - ./ciput_airflow/airflow/plugins:/usr/local/airflow/plugins
        environment:
            - SET_CONTAINER_TIMEZONE=true
            - CONTAINER_TIMEZONE=Asia/Jakarta
            - TZ=Asia/Jakarta
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - REDIS_PASSWORD=redispass
        command: worker

    worker_1:
        build:
            context: docker/airflow
        image: ciput/docker-airflow:1.10.9
        container_name: worker_airflow_1
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ./ciput_airflow/airflow/dags:/usr/local/airflow/dags
            - ./ciput_airflow/airflow/airflow.cfg:/usr/local/airflow/airflow.cfg
            - ./ciput_airflow/airflow/plugins:/usr/local/airflow/plugins
        environment:
            - SET_CONTAINER_TIMEZONE=true
            - CONTAINER_TIMEZONE=Asia/Jakarta
            - TZ=Asia/Jakarta
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - REDIS_PASSWORD=redispass
        command: worker

    worker_2:
        build:
            context: docker/airflow
        image: ciput/docker-airflow:1.10.9
        container_name: worker_airflow_2
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ./ciput_airflow/airflow/dags:/usr/local/airflow/dags
            - ./ciput_airflow/airflow/airflow.cfg:/usr/local/airflow/airflow.cfg
            - ./ciput_airflow/airflow/plugins:/usr/local/airflow/plugins
        environment:
            - SET_CONTAINER_TIMEZONE=true
            - CONTAINER_TIMEZONE=Asia/Jakarta
            - TZ=Asia/Jakarta
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - REDIS_PASSWORD=redispass
        command: worker

    worker_3:
        build:
            context: docker/airflow
        image: ciput/docker-airflow:1.10.9
        container_name: worker_airflow_3
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ./ciput_airflow/airflow/dags:/usr/local/airflow/dags
            - ./ciput_airflow/airflow/airflow.cfg:/usr/local/airflow/airflow.cfg
            - ./ciput_airflow/airflow/plugins:/usr/local/airflow/plugins
        environment:
            - SET_CONTAINER_TIMEZONE=true
            - CONTAINER_TIMEZONE=Asia/Jakarta
            - TZ=Asia/Jakarta
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - REDIS_PASSWORD=redispass
        command: worker

    worker_4:
        build:
            context: docker/airflow
        image: ciput/docker-airflow:1.10.9
        container_name: worker_airflow_4
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ./ciput_airflow/airflow/dags:/usr/local/airflow/dags
            - ./ciput_airflow/airflow/airflow.cfg:/usr/local/airflow/airflow.cfg
            - ./ciput_airflow/airflow/plugins:/usr/local/airflow/plugins
        environment:
            - SET_CONTAINER_TIMEZONE=true
            - CONTAINER_TIMEZONE=Asia/Jakarta
            - TZ=Asia/Jakarta
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - REDIS_PASSWORD=redispass
        networks:
            - airflowcluster
        command: worker


    worker_5:
        build:
            context: docker/airflow
        image: ciput/docker-airflow:1.10.9
        container_name: worker_airflow_5
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ./ciput_airflow/airflow/dags:/usr/local/airflow/dags
            - ./ciput_airflow/airflow/airflow.cfg:/usr/local/airflow/airflow.cfg
            - ./ciput_airflow/airflow/plugins:/usr/local/airflow/plugins
        environment:
            - SET_CONTAINER_TIMEZONE=true
            - CONTAINER_TIMEZONE=Asia/Jakarta
            - TZ=Asia/Jakarta
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - REDIS_PASSWORD=redispass
        networks:
            - airflowcluster
        command: worker


    worker_6:
        build:
            context: docker/airflow
        image: ciput/docker-airflow:1.10.9
        container_name: worker_airflow_6
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ./ciput_airflow/airflow/dags:/usr/local/airflow/dags
            - ./ciput_airflow/airflow/airflow.cfg:/usr/local/airflow/airflow.cfg
            - ./ciput_airflow/airflow/plugins:/usr/local/airflow/plugins
        environment:
            - SET_CONTAINER_TIMEZONE=true
            - CONTAINER_TIMEZONE=Asia/Jakarta
            - TZ=Asia/Jakarta
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - REDIS_PASSWORD=redispass
        networks:
            - airflowcluster
        command: worker


    worker_7:
        build:
            context: docker/airflow
        image: ciput/docker-airflow:1.10.9
        container_name: worker_airflow_7
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ./ciput_airflow/airflow/dags:/usr/local/airflow/dags
            - ./ciput_airflow/airflow/airflow.cfg:/usr/local/airflow/airflow.cfg
            - ./ciput_airflow/airflow/plugins:/usr/local/airflow/plugins
        environment:
            - SET_CONTAINER_TIMEZONE=true
            - CONTAINER_TIMEZONE=Asia/Jakarta
            - TZ=Asia/Jakarta
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - REDIS_PASSWORD=redispass
        networks:
            - airflowcluster
        command: worker
